apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: sample
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: APCA_API_KEY_ID
          valueFrom:
            secretKeyRef:
              name: alpaca-secrets
              key: api-key-id
        - name: APCA_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: alpaca-secrets
              key: api-secret-key

---
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  type: NodePort  # or LoadBalancer if you have that option
  selector:
    app: sample
  ports:
  - port: 80
    targetPort: 5000